name: Release(docker)

on:
  push:
    tags:
      - v*
    branches:
      - master

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'ghcr.io/trim21/gh-bot'

    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: |
          export "TAG_HASH=${DOCKER_FILE_HASH:0:10}-${LOCK_FILE_HASH:0:10}"

          if ! docker pull "${IMAGE}:base-${TAG_HASH}"; then
            echo "build base docker image"
            docker build -t "${IMAGE}:base-${TAG_HASH}" -f etc/base.dockerfile .
            docker push "${IMAGE}:base-${TAG_HASH}"
          fi

          docker tag "${IMAGE}:base-${TAG_HASH}" base-image

        env:
          LOCK_FILE_HASH: "${{ hashFiles('yarn.lock') }}"
          DOCKER_FILE_HASH: "${{ hashFiles('etc/base.dockerfile') }}"
        name: build base docker image

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - run: |
          echo "REF=master" >> $GITHUB_ENV
          echo "TAG=master-$(git describe --match='v*')" >> $GITHUB_ENV
        if: "${{ !startsWith(github.ref, 'refs/tags/') }}"

      - run: |
          echo "REF=latest" >> $GITHUB_ENV
          echo "TAG=v$(cat package.json | jq .version -r)" >> $GITHUB_ENV
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{ref}}-{{sha}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            ARG_REF=${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
